### ISSUE TITLE
Add Search widget for easy searching within the displayed bucket prefix items

### ISSUE THREAD

**Issue by roening** [Rhosys/aws-s3-explorer#12]
Hi!

Would it be possible the have the v2-alpha version from AWS with this cognito integration?
https://github.com/awslabs/aws-js-s3-explorer/tree/v2-alpha

**Comment by wparad** [comment]
I believe this was forked from the v2-alpha branch, but it probably helps anyway to focus on a concrete problem in any case. If there is a feature specifically that's missing for you, we could focus on adding it. There have been lots of improvements here since we forked it, so it would be hard to know at a glance what's missing. Anything you can share explicitly would be helpful.

**Comment by roening** [comment]
Actually, the screenshots of the application in the `release/1.1` branch is not exactly this forked application. I'm running it here and it's really different. In the v2-alpha version we can see the pagination and search features, which is not present in the `release/1.1` branch here. Would I be wrong?

**Comment by wparad** [comment]
There are definitely some differences, for instance, I believe pagination happens automatically, but there definitely isn't a search box if I recall.

If you would like, we can switch this ticket to "Add support for search" instead. My question will be, how do you expect **search** to work. S3 doesn't have a full-text key name search feature, so opinions you have would go along way here.

**Comment by roening** [comment]
Here the objects are listed all in a single page. In a folder with many objects, the page is huge.
The search in the `v2-alpha` happens in the page. The application calls S3 API to list all objects in the current prefix, so the application create pagination and enable the user to search in these objects names. The search doesn't do an API call.

**Comment by wparad** [comment]
Hmm, that seems easy enough to add. I'm updating the ticket to reflect that. If you would be interested in submitting a PR that would definitely help us deliver the improvement quicker.

In any case if you find there are other potential features that would add a lot of value for you, please don't hesitate to open additional issues.
