### ISSUE TITLE
Async S3 listing

### ISSUE THREAD

**Issue by roening** [Rhosys/aws-s3-explorer#14]
Hi,

When we try to access a folder with many objects, it takes a long time without showing anything on the page. To the user, it looks like the folder is empty. In AWS `alpha-v2` [repo](https://github.com/awslabs/aws-js-s3-explorer/tree/v2-alpha), the listing is paginated and the contents of the first page are shown while the application is still listing the contents of the folder.

Would it be possible to add this change?

**Comment by wparad** [comment]
Seems like a great idea.
