### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by mengo-eng** [Rhosys/aws-s3-explorer#15]
Hi @wparad,

Is there any way to run this locally as when I try to build, it launches SAM and Cloudformation to provision resources on AWS? Is there any way, to run it locally like any other vue app? Please, let me know. Thanks

**Comment by wparad** [comment]
You should be able to run this locally running `yarn` and then `yarn start`.

**Comment by mengo-eng** [comment]
Thanks, @wparad. But it takes to create SAM and creates resources in Cloudformation. Is there any way to run it locally to play with UI without really needing to create resources in AWS? Thanks

**Comment by wparad** [comment]
Ah, I see. Let's say you are running it locally, how would you expect to have access to the resources in your AWS account?

**Comment by wparad** [comment]
Closed due to lack of clarification about problem.
