### ISSUE TITLE
Custom Domain Settings for S3 bucket

### ISSUE THREAD

**Issue by melnur** [Rhosys/aws-s3-explorer#2]
Thanks for sharing this project. I am trying to set up a Cognito access to one of my private S3 buckets so that Cognito users can view contents of the bucket and download contents. Your projects appears to be best fit for my requirements. I have set up as per your instructions and added generated callback url to Cognito app client settings. Then I created a user pool and when I try to sign in I see an error message.  Also, not sure at what stage I can point to my private bucket. Please, let me know what I'm missing. Thanks
![image](https://user-images.githubusercontent.com/94445331/141968447-9c2fafcc-256e-4b2b-9217-5b8a12d2e20e.png)

**Comment by wparad** [comment]
:+1: We'll try to see what is going wrong, since this is all hosted in your account, is very difficult for us to investigate, but we'll see what can we can do.

At what stage do you see this error? Could you walk me through the setups to get this? My guess is that:
1. You performed all the required set up steps
2. You went back to the console and entered your AWS accountId
3. You could redirected to your SSO provider
4. You logged in to the SSO provider and got redirected to Cognito
5. The url in the browser looks like https://...cognito...aws...pool-id or something like that?

Is that correct? If not, you could walk me through where the error shows up.

Either way can you point me to what SSO provider you are using, be it Google, Facebook, etc... I want to try setting up that provider myself and see if I run into similar probems.

**Comment by melnur** [comment]
Thanks for reply. I have completed steps 1 and 2. Once Cloudformation stack completed creating resources I copied the callback url from Step 3 (the one in shown in the screenshot below) and pasted into "Sign out URL" and "Callback URL" sections in Cognito (second screenshot). I didn't connect with any identity providers, instead created some users in Cognito User Pool. Then when I click to Hosted UI, I see login window which successfully logs me in only to show the error in my first post. Did I skip any steps? Where I am supposed to link this app to my existing private bucket? Please. let me know. Thanks in advance.
![image](https://user-images.githubusercontent.com/94445331/142071031-e6712768-4e69-44b5-b04a-44d55929523f.png)
**Cognito Screenshot**
![image](https://user-images.githubusercontent.com/94445331/142071464-b4ffb9db-7e59-458e-bd4f-2504de74bd7d.png)

**Comment by wparad** [comment]
It doesn't look like you skipped a step, but the callback url entering was the incorrect thing to do. This callback url is to configure an SSO connection _to_ cognito. You've entered it in the callback url spot _to the s3 explorer_ that broke login with cognito. You'll want to reset these callback and signout urls to be:
`http://localhost:8080, http://localhost:8080/, https://console.rhosys.ch, https://console.rhosys.ch/, https://rhosys.github.io/aws-s3-explorer, https://rhosys.github.io/aws-s3-explorer/`

After resetting those properties to the correct values, try again, and let me know if there is still a problem.

> Where I am supposed to link this app to my existing private bucket? Please. let me know. Thanks in advance.

After login you'll see the bucket selection screen which will let you specify the bucket you want to connect to. If the bucket isn't already configured correctly, there will be additional steps there.

**Comment by melnur** [comment]
Thanks again. So, I started from scratch and didn't change the callback url this time (I guess when userpool is used, step 3 and 4 are not applicable - so I have only completed steps 1 & 2 which created the whole thing by Cloudformation). I can see login screen and it accepts my credentials which I created in userpool. But then it says "site can't be reached". I am sure I might have missed something. I feel like I'm close. Please, let me know what is missing here. Thanks
![image](https://user-images.githubusercontent.com/94445331/142191159-e2b55d1a-61f1-4ae4-84ce-fd86c3fc6f83.png)
![image](https://user-images.githubusercontent.com/94445331/142191245-6edc17a1-75f6-4c75-b0a4-c531d4dfc611.png)

**Comment by wparad** [comment]
Somehow the `redirect_uri` is being set to `localhost:8080` instead of `console.rhosys.ch`.  Are you logging in through `console.rhosys.ch` or running this locally on your machine?

That url from the first screenshot is wrong, how was it generated?
When I click login and get to cognito it looks like this for me:
```
https://ACCOUNT_ID-s3explorer.auth.eu-west-1.amazoncognito.com/login
?response_type=code
&client_id=CLIENT_ID
&state=STATE_NONCE
&code_challenge_method=S256
&code_challenge=CODE_CHALLENGE
&redirect_uri=https://console.rhosys.ch/
```

But yours has also `scope` and the wrong `redirect_uri`

**Comment by melnur** [comment]
Hi, thanks a lot. It worked perfectly. I could define my bucket, but it opens in https://console.rhosys.ch/. How can I change it my own domain name or some sort of aws url that I can use in Route53? Also, is it possible to grant only read access ( or remove options to delete and upload objects)? Thanks in advance.

**Comment by wparad** [comment]
> How do I grant read only access
There is a role generated called `S3_Explorer_Authenticated_User`, that you can change the permissions to whatever you want. If you have a more complicated setup you want there are lots of different things you can do.

> Using a custom domain
One option would be to fork this repository and deploy it to your own infrastructure (github or s3), although that effort wouldn't be trivial. I'm wondering if a CloudFront/ACM/Route53 here would work pointing at the existing url. I haven't tried this out, but I can definitely see if it would be possible, if that is something you are interested in.

**Comment by melnur** [comment]
Thanks Warren, CustomDomain is great new feature. However, when I try to login through my Hosted UI, it is still opening http://localhost:8080/. When I replace that with my custom domain in Hosted UI URL, it opens blank page as below. It only works if user logs into AWS first in same browser session. In that case, Cognito doesn't really serve any purpose. I might be missing something... 
![image](https://user-images.githubusercontent.com/94445331/142254832-86c4ac08-0abc-4214-8336-c0fb513ed13a.png)

**Comment by wparad** [comment]
What's the domain?

**Comment by wparad** [comment]
Let me know if this is still an issue even in the latest version and we need to repoen this issue. I want to make sure this gets resolved for your use case.

**Comment by melnur** [comment]
Thanks @wparad . I have it only in us-east-1 now and the same issue persists. Whenever, I open in a new private window, bucket setup starts from scratch. I only see a blank page (screenshot 1)  and when I refresh the page, the setup screen appears (screenshot 2). Once I enter account id and bucket name, it works perfectly - but whole thing must be started again if I open in new tab (private). When I compare cookies, the one which opened in new private window missing "csrf-state" and "csrf-state-legacy" cookies. This is really good solution for my project but unfortunately I can't set it up correctly. :( Any suggestions are appreciated. Thanks
![image](https://user-images.githubusercontent.com/94445331/142904487-bfd9b521-b5de-46be-951f-9882516287f6.png)
![image](https://user-images.githubusercontent.com/94445331/142904801-b608afa2-6f58-4081-8aac-e56e189ca655.png)
![image](https://user-images.githubusercontent.com/94445331/142905226-57b16332-f749-431f-8aa8-8f8c5c0afcf1.png)
![image](https://user-images.githubusercontent.com/94445331/143001257-9ea77edf-570d-4c4f-9d48-86e8b2a9cf0e.png)

**Comment by wparad** [comment]
Okay we've made a small change that should automatically take effect. When using a custom domain as you are, the user will automatically be directed to login if they haven't logged in before. Take a look at that, and see if it is doing everything you expect.

**Comment by melnur** [comment]
Thanks @wparad . There is an improvement now. Although I can briefly see setup screen I'm instantly redirected to the cognito screen. Then once I am in, I am offered to choose a bucket to look at. So, it doesn't remember previously configured bucket name. Is there a way, to set bucket name once and never asked again? Thanks in advance.

**Comment by wparad** [comment]
To make it a bit cleaner, we've replaced the flash with a loader, there isn't much else we can as the user must navigate through this screen before being sent to cognito (an issue with cognito). So hopefully that's sufficient.

Regarding the "does not remember previous bucket". It definitely will, but not if you are in _incognito_ and that's because storage isn't saved between sessions. If you are finding the bucket isn't remembered between subsequent sessions of the same user in public browsing mode, could you open another ticket with the reproduction flow?

With that I'll finally close this one :)

**Comment by melnur** [comment]
Thanks again @wparad. It is almost perfect. But as I mentioned, is there a way to specify bucket name as a parameter in Cloudformation (hardcode) so that it is no longer needed to be defined after installation or between sessions in private mode? Thanks

**Comment by wparad** [comment]
> Thanks again @wparad. It is almost perfect. But as I mentioned, is there a way to specify bucket name as a parameter in Cloudformation (hardcode) so that it is no longer needed to be defined after installation or between sessions in private mode? Thanks

@melnur I'm assuming this will solve your issue: https://github.com/Rhosys/aws-s3-explorer/issues/4 correct? Or is there more nuance there?
