### ISSUE TITLE
Allow default list of buckets

### ISSUE THREAD

**Issue by wparad** [Rhosys/aws-s3-explorer#4]
Allow defining a default list of buckets for the account that are always available to anyone that signs in.

**Comment by melnur** [comment]
Thanks @wparad . That would be perfect.

**Comment by wparad** [comment]
Added so that a default list of buckets can be set using a configuration file in S3. The instructions on the file to create are documented here: https://github.com/Rhosys/aws-s3-explorer/blob/release/1.1/docs/configuration.md

**Comment by melnur** [comment]
That's perfect. Thanks a lot. Is there any way to limit access to specific folders in a bucket? I tried to do it through IAM role of S3_Explorer_Authenticated_User-REGION, but couldn't succeed. Also, can multiple files be downloaded as zip? Thanks in advance. :)

**Comment by wparad** [comment]
>  Is there any way to limit access to specific folders in a bucket? I tried to do it through IAM role of S3_Explorer_Authenticated_User-REGION, but couldn't succeed.

Yes, and this would be the right place to make that change, if you have the policy which isn't working shared here, I can try to take a look if something is awry with it.

> Also, can multiple files be downloaded as zip?

Definitely, can you open a separate github issue for this?

**Comment by melnur** [comment]
> Definitely, can you open a separate github issue for this?
Thanks a lot. So, I need read-only access so my policy for entire bucket is as below:
`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetObject"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow",
            "Sid": "S3Access"
        }
    ]
}
`
I tried to add "arn:aws:s3:::my-bucket/my-folder/*" to Resource above then the bucket became inaccessible. I tried to add another statement but then it didn't restrict to access to other folders. I used conditions as well but didn't work.
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:ListBucket"
            ],
            "Resource": "*"
        },
        {
            "Sid": "myfolder",
            "Action": [
                "s3:ListBucket"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::my-bucket"
            ],
            "Condition": {
                "StringEquals": {
                    "s3:prefix": [
                        "my-folder/"
                    ],
                    "s3:delimiter": [
                        "/"
                    ]
                }
            }
        }
    ]
}`
So, not sure what is the best way to implement sub folder access. Please, let me know if it can be implemented. Thanks

**Comment by wparad** [comment]
Checkout https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html
So a couple of things:
* You probably want to use `StringLike` not `StringEquals` especially for `GetObject`.
* For ListBucket, you need to allow at least `""` (empty prefix) or else your users won't even be able to open the first level search.

If you go into the console, you might be able to figure out exactly which operation is failing, that would tell us more about exactly which call is failing and with which parameters.

hope that helps
