### ISSUE TITLE
Integration with existing Cognito User Pool

### ISSUE THREAD

**Issue by melnur** [Rhosys/aws-s3-explorer#7]
@wparad thanks for batch download feature. I was trying to integrate the app with existing Cognito user pool. I tried to edit configuration file in S3 bucket and edit S3_Explorer_Authenticated_User-${AWS::Region} to associate with identityPoolId (trust relationship conditions). However, it didn't work. When I try to go to my app, it is still going to CF created Amazon Cognito domain rather than existing one (which I definedin config file). I assume it is because, Cloudfront is directing there. I couldn't figure out how to use an existing user pool so far. Not sure even if it is possible. Please, let me know if that can be implemented. Thanks in advance

**Comment by wparad** [comment]
The three things that need to change should be:
* Configuration.json update cognito pool Id (also the cognito identity pool if that should be different as well)
* The login url for the app called the `Cognito Domain` at:
`Cognito User Pool > App Integration > Configuration for all app clients > Domain`. This must be of the form: `https://AWS_ACCOUNT_ID-s3explorer.auth.REGION.amazoncognito.com`

* The cognito app data associated with the cogino pool has to allow your app. That is the value found at:
`Cognito User Pool > App Integration > App clients and analytics > Select the App Client`

**Comment by melnur** [comment]
Thanks @wparad. I think there is some improvement now. At least it doesn't tell me that there is a mismatch. I can now login in. But when I try to click folder name nothing happens (like when correct IAM permissions are not set - I checked, looks correct in IAM). I looked at the console and see following. Does it suggest anything useful regarding inaccessibility of the data in the bucket/folder? Thanks
![image](https://user-images.githubusercontent.com/94445331/145478514-d9463bd6-9671-49e2-b1f8-a568f5384c29.png)

**Comment by wparad** [comment]
What do those `400` error responses look like in the network tab?

**Comment by melnur** [comment]
Thanks @wparad . It looks like this :(
![image](https://user-images.githubusercontent.com/94445331/145480689-5427cd97-390c-489b-bd9e-adf6bcaf4565.png)

**Comment by wparad** [comment]
yeah but if you click on one and see what the 400 response error is, what does it say?
![image](https://user-images.githubusercontent.com/5056218/145480912-12043262-7ec2-432d-ab8a-b2eeb3706de2.png)

**Comment by melnur** [comment]
> yeah but if you click on one and see what the 400 response error is, what does it say? 
![image](https://user-images.githubusercontent.com/94445331/145481226-82ed65c6-ce34-419c-ad83-d6b364830f1c.png)

**Comment by wparad** [comment]
It means that you haven't configured the identity pool to work with your new cognito pool. Go to the cognito pool and update it to work with the new pool.

`Cognito > Federated Identity Pools => Select Pool => Edit (top right hand corner) => Authentication providers => Cognito`
* Set the pool id
* Set the app client id from your custom pool

Then retry.

**Comment by melnur** [comment]
Thanks. I have made those changes. Now I have another error :)
![image](https://user-images.githubusercontent.com/94445331/145483236-f537418b-0ccf-4493-a5a9-53dcf35ec3dc.png)

**Comment by melnur** [comment]
I have replaced original identityPoolId in config file with the one below and used the same new one in IAM Trust. Is it not right?
I can even see token in console now. However, somehow IAM is not allowing me. I feel like I am very close to the solution, but both original identity pool ids and new ones didn't work. :(
![image](https://user-images.githubusercontent.com/94445331/145489301-c540f12e-244a-4a6a-acbb-abce5f8bfb39.png)

![image](https://user-images.githubusercontent.com/94445331/145489485-3f711bc0-fe86-4f77-bc7e-c8c681e0c165.png)

![image](https://user-images.githubusercontent.com/94445331/145489880-e0340288-246b-4cbc-9f95-55fab2c0fe5b.png)

**Comment by wparad** [comment]
That's the wrong value. That's the cognito identity `userId` you copied, you want the cognito `identity pool id`. Grab the value from the url address bar (the format is the same, so I'm not surprised it looked correct).

**Comment by melnur** [comment]
Thanks again. Yes, that was wrong one. Here is right one, which is from existing Cognito. It still didn't work. What is interesting is, the identity pool which was created by CF has a role attached but the existing one doesn't. Changing trust in IAM doesn't change this. I wonder how that can be added. I think once role is added to existing identity pool, the problem may be solved. Appreciate your help. Thanks

![image](https://user-images.githubusercontent.com/94445331/145491531-d05c3904-e207-4803-afca-e4bc52d7685b.png)

![image](https://user-images.githubusercontent.com/94445331/145491903-3432d655-a4c2-4bb2-8681-7aaf5e53c186.png)

**Comment by melnur** [comment]
Actually, I figured out the problem. As I pointed out above, IAM role was not set for my existing identity pool. I used following CLI commands to attach IAM role - apparently editing Trust was not sufficient. I can't thank you enough. Appreciate your help
`aws cognito-identity set-identity-pool-roles \
    --identity-pool-id "us-west-2:11111111-1111-1111-1111-111111111111" \
    --roles authenticated="arn:aws:iam::111111111111:role/Cognito_MyIdentityPoolAuth_Role"`

**Comment by wparad** [comment]
:tada:
