### ISSUE TITLE
Display percentage of data uploaded

### ISSUE THREAD

**Issue by Manouchka94** [Rhosys/aws-s3-explorer#9]
Hello @wparad,

I use your project to upload big files (100 mo and more) to S3 bucket.
During the upload step the percentage of data uploaded is initially fixed at 0% and when upload is finished it's set to 100%.

In the progressUpdatedHandler function in uploadModal.vue file I use two properties of the evt (evt.loaded and evt.total) to calculate the percentage of data uploaded.

Thus, the percentage value is updated dynamically and helps to follow the progress of the upload for big files.
What do you think about this proposal ?

```javascript
const progressUpdatedHandler = evt => {
  DEBUG.log('File:', file, 'Part:', evt.part, evt.loaded, 'of', evt.total);
  // Use evt.loaded and evt.total to calculate the percentage of data uploaded
  state.completionPercentageMap[fileIndex] = Math.round((evt.loaded * 100) / evt.total);
};
```

**Comment by wparad** [comment]
Seems like a great idea. You might need to add some protections to ensure `evnt.loaded || 0` is always a number (and also handle `evt.total`, but this is awesome.

Feel free to make a PR, and we can test this out.
